name: Echo Variables

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - id: fetch-latest-release
        uses: thebritican/fetch-latest-release@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }
        
      - name: print steps.fetch-latest-release.outputs.tag_name
        run: echo ${{ steps.previoustag.outputs.tag }}

      - name: print ${GITHUB_REF##*/}
        run: echo ${GITHUB_REF##*/}

      - name: print $GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

